Strings = {
    -- New Discord log strings(1.2.7)
    log_killed_title = 'Player Killed',
    log_killed_desc = '> *%s [%s] killed %s [%s]\n\n**Killer\'s Information:**\nName: `%s`\nPlayer ID: `%s`\nIdentifier: `%s`\nSteam: `%s`\nDiscord: `%s`\nLicense: `%s`\nLicense2: `%s`\nXBL: `%s`\nFiveM: `%s`\nIP: ||%s||\n\n**Victim\'s Information:**\nCharacter Name: `%s`\nPlayer ID: `%s`\nIdentifier: `%s`\nSteam: `%s`\nDiscord: `%s`\nLicense: `%s`\nLicense2: `%s`\nXBL: `%s`\nFiveM: `%s`\nIP: ||%s||\n\n> **Death Cause:** `%s`',
    log_suicide_title = 'Player Committed Suicide',
    log_suicide_desc = '> %s [%s] killed themselves\n\n**Player Information:**\nName: `%s`\nPlayer ID: `%s`\nIdentifier: `%s`\nSteam: `%s`\nDiscord: `%s`\nLicense: `%s`\nLicense2: `%s`\nXBL: `%s`\nFiveM: `%s`\nIP: ||%s||\n\n> **Death Cause:** `%s`',
    unknown = 'UNKNOWN',
    -- Trad FR
    JobMenuTitle = 'Menu Taxi',
    AnnounceMenuTitle = 'Annonce',
    GoBack = 'Retour en arrière',
    key_map_text = 'Menu Taxi',
    no_nearby = 'Pas trouvé',
    no_nearby_desc = 'Il semble n\'y avoir personne autour',
    not_taxi = 'Non autorisé',
    not_taxi_desc = 'Vous n\'êtes pas formé pour l\'utiliser!',
    drop_bag_ui = '[E] - Déposer la caisse à outil',
    pickup_bag_target = 'Récupérer',
    move_target = 'Bouger',
    interact_bag_target = 'Ouvrir',
    successful = 'Réussi',
    item_grab = 'Vous avez pris un outil de votre boîte à outils',
    wrong_equipment = 'Mauvais équipement!',
    wrong_equipment_desc = 'Avez-vous même été formé?',
    request_supplies_target = 'Matériaux',
    currency = '$',
    not_enough_funds = 'Fonds insuffisants',
    not_enough_funds_desc = 'Vous n\'avez pas assez de fonds!',
    taxi_garage = 'Taxi',
    action_cancelled = 'Action annulée',
    action_cancelled_desc = 'Vous avez annulé votre dernière action!',
    max_taxi = 'Trop de personnel',
    max_taxi_desc = 'Il y a déjà suffisamment de mécaniciens en service !',
    player_busy = 'Occupé',
    player_busy_desc = 'Vous êtes actuellement trop occupé pour effectuer cette action!',
    cloakroom = 'Vestiaire',
    civilian_wear = 'Vêtements civils',
    announce = 'Annonce',
    announce_desc = 'Annoncez votre présence à la ville',
    announce_open = 'Ouvert',
    announce_close = 'Fermer',
    announce_custom = 'Personnalisé',
    bill_customer = 'Facture',
    bill_customer_desc = 'Facturez un client pour les réparations',
    invalid_entry = 'Entrée invalide',
    invalid_entry_desc = 'Vous devez entrer un montant valide!',
    taxi_services = 'Taxi Services',
    taxi = 'Delamain Taxi',

    interact_stretcher_ui = '[E] - Interagir',
    open_shop_ui = '[E] - Ouvrir le magasin',
    
}
