Strings = {
    -- New Discord log strings(1.2.7)
    log_killed_title = 'Player Killed',
    log_killed_desc = '> *%s [%s] killed %s [%s]\n\n**Killer\'s Information:**\nName: `%s`\nPlayer ID: `%s`\nIdentifier: `%s`\nSteam: `%s`\nDiscord: `%s`\nLicense: `%s`\nLicense2: `%s`\nXBL: `%s`\nFiveM: `%s`\nIP: ||%s||\n\n**Victim\'s Information:**\nCharacter Name: `%s`\nPlayer ID: `%s`\nIdentifier: `%s`\nSteam: `%s`\nDiscord: `%s`\nLicense: `%s`\nLicense2: `%s`\nXBL: `%s`\nFiveM: `%s`\nIP: ||%s||\n\n> **Death Cause:** `%s`',
    log_suicide_title = 'Player Committed Suicide',
    log_suicide_desc = '> %s [%s] killed themselves\n\n**Player Information:**\nName: `%s`\nPlayer ID: `%s`\nIdentifier: `%s`\nSteam: `%s`\nDiscord: `%s`\nLicense: `%s`\nLicense2: `%s`\nXBL: `%s`\nFiveM: `%s`\nIP: ||%s||\n\n> **Death Cause:** `%s`',
    unknown = 'UNKNOWN',

    JobMenuTitle = 'Menu circlebar',
    AnnounceMenuTitle = 'Announce',
    GoBack = 'Retour',
    key_map_text = 'Menu job circlebar',
    no_nearby = 'Pas trouvé',
    no_nearby_desc = 'Il semble n\'y avoir personne autour',
    not_circlebar = 'Non autorisé',
    not_circlebar_desc = 'Vous n\'êtes pas formé pour l\'utiliser!',
    successful = 'Réussi',
    request_supplies_target = 'Barman',
    currency = '$',
    not_enough_funds = 'Fonds insuffisants',
    not_enough_funds_desc = 'Vous n\'avez pas assez de fonds!',
    circlebar_garage = 'Garage circlebar',
    action_cancelled = 'Action annulée',
    action_cancelled_desc = 'Vous avez annulé votre dernière action!',
    max_circlebar = 'Trop de personnel',
    max_circlebar_desc = 'There are already enough circlebars on duty!',
    player_busy = 'Occupé',
    player_busy_desc = 'Il y a déjà suffisamment de mécaniciens en service !',
    cloakroom = 'Vestiaire',
    civilian_wear = 'Vêtements civils',
    announce = 'Annonce',
    announce_desc = 'Annoncez votre présence à la ville',
    announce_open = 'Ouvert',
    announce_close = 'Fermer',
    announce_custom = 'Personnalisé',
    bill_customer = 'Facture',
    bill_customer_desc = 'Facturez un client pour les réparations',
    invalid_entry = 'Entrée invalide',
    invalid_entry_desc = 'Vous devez entrer un montant valide!',
    circlebar_services = 'circlebar Services',
    circlebar = 'circlebar',

    open_shop_ui = '[E] - Ouvrir le magasin',
    
}
