Emotions = { -- [emotionId] = {label Expression, emotionClip}
    ["Angry"] = { "Angry Expression", "mood_angry_1" },
    ["Drunk"] = { "Drunk Expression", "mood_drunk_1" },
    ["Dumb"] = { "Dumb Expression", "pose_injured_1" },
    ["Electrocuted"] = { "Electrocuted Expression", "electrocuted_1" },
    ["Grumpy"] = { "Grumpy Expression", "effort_1" },
    ["Grumpy2"] = { "Grumpy2 Expression", "mood_drivefast_1" },
    ["Grumpy3"] = { "Grumpy3 Expression", "pose_angry_1" },
    ["Happy"] = { "Happy Expression", "mood_happy_1" },
    ["Injured"] = { "Injured Expression", "mood_injured_1" },
    ["Joyful"] = { "Joyful Expression", "mood_dancing_low_1" },
    ["Mouthbreather"] = { "Mouthbreather Expression", "smoking_hold_1" },
    ["Never Blink"] = { "Never Blink Expression", "pose_normal_1" },
    ["OneEye"] = { "One Eye Expression", "pose_aiming_1" },
    ["Shocked"] = { "Shocked Expression", "shocked_1" },
    ["Shocked2"] = { "Shocked2 Expression", "shocked_2" },
    ["Sleeping"] = { "Sleeping Expression", "mood_sleeping_1" },
    ["Sleeping2"] = { "Sleeping2 Expression", "dead_1" },
    ["Sleeping3"] = { "Sleeping3 Expression", "dead_2" },
    ["Smug"] = { "Smug Expression", "mood_smug_1" },
    ["Speculative"] = { "Speculative Expression", "mood_aiming_1" },
    ["Stressed"] = { "Stressed Expression", "mood_stressed_1" },
    ["Sulking"] = { "Sulking Expression", "mood_sulk_1" },
    ["Weird"] = { "Weird Expression", "effort_2" },
    ["Weird2"] = { "Weird2 Expression", "effort_3" },
}